version: "3.8"
services:
  api_tickets:
    depends_on:
      - mysql
    image: ggmartinez/laravel:php-82
    container_name: api_tickets
    ports:
      - "8000:8000"
    volumes:
      - "./:/app"
  mysql:
    image: mysql:8
    container_name: database
    ports:
      - "3306:3306"
    volumes:
      - "./mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=origins
